/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rafaeljpc.ktor.tutorial

import io.ktor.server.engine.commandLineEnvironment
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main(args: Array<String>) {
    embeddedServer(Netty, commandLineEnvironment(args)).start(wait = true)
}
